project:
  type: website
  output-dir: docs

website:
  title: "Zia Yan"
  navbar:
    background: "#2d2d2d"
    foreground: "white"
    left:
      - text: "Myself"
        file: index.qmd
      - text: "Projects"
        file: about.qmd
      - text: "Poisson Regression Analysis"
        file: hw3_questions.qmd
    right:
      - icon: envelope
        href: mailto:ziy048@ucsd.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/zixiaoyan
      - icon: github
        href: https://github.com/ziayan-analytics

format:
  html:
    theme: darkly
    anchor-sections: false
    


